manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Toucan trackpad (Cirque Pinnacle glidepoint) driver, pinned to beekeeb's
    # "toucan" branch per config/west.yml in github.com/beekeeb/zmk-keyboard-toucan
    - name: cirque-input-module
      remote: geeksville
      revision: toucan
    # Toucan's battery/BLE-profile RGB status LED widget (rgbled_adapter shield)
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
  self:
    path: config
