manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: mouse
      url-base: https://github.com/ftc

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
